const DEFAULT_BACKEND = 'http://localhost:8765';

async function cfg() {
  return new Promise((r) => chrome.storage.local.get(["userToken", "userInfo", "autoScan"], r));
}

function baseUrl() {
  return DEFAULT_BACKEND;
}

async function call(path, body, method = "POST") {
  const c = await cfg();
  const headers = { "Content-Type": "application/json" };
  if (c.userToken) headers["X-User-Token"] = c.userToken;
  const res = await fetch(baseUrl() + path, { method, headers, body: body ? JSON.stringify(body) : undefined });
  if (!res.ok) throw new Error(`${res.status} ${await res.text()}`);
  return res.json();
}

async function extractYouTubeCookies() {
  try {
    const cookies = await chrome.cookies.getAll({ url: "https://www.youtube.com" });
    if (!cookies.length) return null;
    const lines = ["# Netscape HTTP Cookie File", "# Generated by NASTube extension", ""];
    for (const c of cookies) {
      const domain = c.domain || ".youtube.com";
      const flag = domain.startsWith(".") ? "TRUE" : "FALSE";
      const path = c.path || "/";
      const secure = c.secure ? "TRUE" : "FALSE";
      const expiry = c.expirationDate ? Math.floor(c.expirationDate) : "0";
      lines.push(`${domain}\t${flag}\t${path}\t${secure}\t${expiry}\t${c.name}\t${c.value}`);
    }
    return lines.join("\n");
  } catch (e) {
    console.error("[NASTube] cookie extraction error:", e);
    return null;
  }
}

chrome.runtime.onMessage.addListener((msg, _sender, sendResponse) => {
  (async () => {
    try {
      if (msg.action === "enqueue") sendResponse(await call("/api/enqueue", msg.payload));
      else if (msg.action === "enqueueBulk") sendResponse(await call("/api/enqueue_bulk", msg.payload));
      else if (msg.action === "syncCookies") {
        const cookiesText = await extractYouTubeCookies();
        if (!cookiesText) { sendResponse({ ok: false, error: "Aucun cookie YouTube trouvé" }); return; }
        const r = await call("/api/cookies/upload", { cookies: cookiesText });
        sendResponse(r);
      }
      else sendResponse({ ok: false, error: "unknown action" });
    } catch (e) {
      sendResponse({ ok: false, error: String(e) });
    }
  })();
  return true;
});
